include $(GOROOT)/src/Make.inc

TARG=polecalc
GOFILES=\
bisection.go\
bracket.go\
cubicspline.go\
environment.go\
integrate.go\
kramerskronig.go\
list_cache.go\
mesh2d.go\
mesh_aggregates.go\
mpljson.go\
selfconsistent.go\
spectrum.go\
utility.go\
tridiagonal.go\
vector.go\
vector_cache.go\
zerotemp.go\
zerotemp_greens.go\
zerotemp_plots.go\

include $(GOROOT)/src/Make.pkg
