include $(GOROOT)/src/Make.inc

TARG=polecalc
GOFILES=\
bisection.go\
bracket.go\
cubicspline.go\
environment.go\
mesh2d.go\
mesh_functions.go\
mpljson.go\
selfconsistent.go\
spectrum.go\
utility.go\
tridiagonal.go\
zerotemp.go\

include $(GOROOT)/src/Make.pkg
